# Generated by Django 3.0.8 on 2020-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_info',
            name='assert_result_list',
            field=models.CharField(max_length=200, null=True, verbose_name='断言结果列表'),
        ),
    ]
