# Generated by Django 3.0.8 on 2020-07-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0002_auto_20200713_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface_info',
            name='assert_filed_type_list',
        ),
        migrations.RemoveField(
            model_name='interface_info',
            name='input_fileld_type_list',
        ),
        migrations.AlterField(
            model_name='interface_info',
            name='assert_filed_list',
            field=models.CharField(max_length=200, null=True, verbose_name='断言字段列表'),
        ),
        migrations.AlterField(
            model_name='interface_info',
            name='created_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='interface_info',
            name='input_fileld_list',
            field=models.CharField(max_length=200, null=True, verbose_name='输入字段列表'),
        ),
        migrations.AlterField(
            model_name='interface_info',
            name='match_list',
            field=models.CharField(max_length=200, null=True, verbose_name='匹配内容列表'),
        ),
    ]
