# Generated by Django 3.0.8 on 2020-07-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0003_auto_20200715_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_info',
            name='belong_group',
            field=models.CharField(max_length=50, null=True, verbose_name='所属分类'),
        ),
        migrations.AddField(
            model_name='interface_info',
            name='interface_url',
            field=models.CharField(default=1, max_length=150, verbose_name='接口url'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interface_info',
            name='belong_subsys',
            field=models.CharField(max_length=50, verbose_name='所属子系统'),
        ),
    ]
