# Generated by Django 3.0.8 on 2020-07-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0005_auto_20200715_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_info',
            name='updated_time',
            field=models.DateTimeField(null=True, verbose_name='更新时间'),
        ),
    ]
