# Generated by Django 3.0.8 on 2020-07-16 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0006_auto_20200715_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_info',
            name='interface_mock',
            field=models.CharField(max_length=200, null=True, verbose_name='接口url'),
        ),
    ]
