# Generated by Django 3.0.8 on 2020-07-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0007_interface_info_interface_mock'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_info',
            name='created_person',
            field=models.CharField(default='usr001', max_length=30, verbose_name='创建人'),
            preserve_default=False,
        ),
    ]
