# Generated by Django 3.0.8 on 2020-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0009_auto_20200717_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(max_length=50, verbose_name='领域名')),
                ('domain_brief', models.CharField(max_length=100, null=True, verbose_name='领域简介')),
            ],
            options={
                'verbose_name': '领域表',
                'ordering': ['-id'],
            },
        ),
        migrations.RenameModel(
            old_name='User_Group_Relation',
            new_name='User_Domain_Group_Relation',
        ),
        migrations.AlterModelOptions(
            name='user_domain_group_relation',
            options={'ordering': ['-id'], 'verbose_name': '用户域组关系表'},
        ),
        migrations.RenameField(
            model_name='user_domain_group_relation',
            old_name='group_belong',
            new_name='belong_group',
        ),
        migrations.RemoveField(
            model_name='user_info',
            name='user_role',
        ),
        migrations.AddField(
            model_name='user_group_info',
            name='group_name',
            field=models.CharField(default='AA', max_length=50, verbose_name='组名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_group_info',
            name='group_brief',
            field=models.CharField(max_length=50, null=True, verbose_name='组简介'),
        ),
    ]
