# Generated by Django 3.0.8 on 2020-07-17 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0010_auto_20200717_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_info',
            name='belong_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horsequick.Domain_Info', verbose_name='所属领域'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_domain_group_relation',
            name='belong_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horsequick.Domain_Info', verbose_name='所属领域'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_group_info',
            name='belong_domain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horsequick.Domain_Info', verbose_name='所属领域'),
            preserve_default=False,
        ),
    ]
