# Generated by Django 3.0.8 on 2020-07-22 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0011_auto_20200717_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface_info',
            name='belong_group',
        ),
        migrations.CreateModel(
            name='Category_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('belong_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsequick.Domain_Info', verbose_name='所属领域')),
            ],
            options={
                'verbose_name': '接口类别表',
                'ordering': ['-id'],
            },
        ),
    ]
