# Generated by Django 3.0.8 on 2020-07-22 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0012_auto_20200722_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_info',
            name='belong_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='horsequick.Category_Info', verbose_name='所属类别'),
            preserve_default=False,
        ),
    ]
