# Generated by Django 3.0.8 on 2020-07-24 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0014_auto_20200722_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_info',
            name='belong_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='horsequick.Category_Info', verbose_name='所属类别'),
        ),
        migrations.AlterField(
            model_name='interface_info',
            name='belong_domain',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.SET_DEFAULT, to='horsequick.Domain_Info', verbose_name='所属领域'),
        ),
        migrations.CreateModel(
            name='Sub_Sys_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_sys_name', models.CharField(max_length=50, verbose_name='子系统名称')),
                ('svn_address', models.CharField(max_length=100, verbose_name='子系统SVN地址')),
                ('git_address', models.CharField(max_length=100, verbose_name='子系统GIT地址')),
                ('belong_domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horsequick.Domain_Info', verbose_name='所属领域')),
            ],
            options={
                'verbose_name': '子系统信息表',
                'ordering': ['-id'],
            },
        ),
    ]
