# Generated by Django 3.0.8 on 2020-07-24 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0015_auto_20200724_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_info',
            name='belong_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horsequick.Category_Info', verbose_name='所属类别'),
        ),
    ]
