# Generated by Django 3.0.8 on 2020-07-29 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0016_auto_20200724_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface_info',
            name='belong_subsys',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horsequick.Sub_Sys_Info', verbose_name='所属子系统'),
        ),
    ]
