# Generated by Django 3.0.8 on 2020-07-29 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0017_auto_20200729_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface_info',
            name='belong_git_base',
        ),
        migrations.RemoveField(
            model_name='interface_info',
            name='belong_svn_base',
        ),
    ]
