# Generated by Django 3.0.8 on 2020-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horsequick', '0018_auto_20200729_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface_info',
            name='updated_person',
            field=models.CharField(max_length=30, null=True, verbose_name='更新人'),
        ),
    ]
